### ISSUE TITLE
is this function 'atomic'?

### ISSUE THREAD

**Issue by job** [RIPE-NCC/rpki-publication-server#37]
Hi RIPE NCC,

**disclaimer: i am not well versed in scala**

Reading the `promoteStagingToOnline()` function
https://github.com/RIPE-NCC/rpki-publication-server/blob/ac3d121f90777a6f131b519d62030ef9bb447f41/src/main/scala/net/ripe/rpki/publicationserver/store/fs/RsyncRepositoryWriter.scala#L63-L68

To me it reads as if the function first removes the 'online' directory (which depending on the size of the directory might take N amount of time), and then moves the "tempRepoDir" into its final place. Such a sequence of events might not be appear 'atomic' from the perspective of an already-sync-in-progress connected client.

Perhaps this is the point in the code where instead of "delete + move", a "point symlink to new dir" (by overwriting the symlink that was pointing to the previous state) strategy could help increase consistency from the fetching party's perspective?

Kind regards,

Job

**Comment by ties** [comment]
Hi Job,

A rather late reply, but you are right. The method that `rpki-publication-server` uses to create rsync repositories is unsafe. It is nice for debugging, but it is a foot-cannon, and should not be used for 'production' repositories.

Kind regards,
Ties
